### **파이썬을 활용한 빅데이터 분석**

##### Chapter 05 인공신경망을 이용한 데이터분석

##### 2020710058 Applied Data Science Doo-yeonog, Lee

In [3]:
# Load Iris Data
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
# Check the key value of iris data 
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [15]:
import pandas as pd
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
# Make dataset
X = iris.data
y = iris.target

In [23]:
import numpy as np
print(np.unique(y))
print(iris.target_names)

[0 1 2]
['setosa' 'versicolor' 'virginica']


In [27]:
# Split data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(len(X_train), len(X_test), len(X_test)/(len(X_test)+len(X_train)))

112 38 0.25333333333333335


In [31]:
# Nomalize
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
# 정규화 해주는 이유: https://goodtogreate.tistory.com/entry/Neural-Network-%EC%A0%81%EC%9A%A9-%EC%A0%84%EC%97%90-Input-data%EB%A5%BC-Normalize-%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

In [34]:
# MLP and Hidden Layers
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes = (10, 10, 10)) # 3 Hidden-layers and 10 nodes for each Hidden.L.

In [35]:
mlp.fit(X_train, y_train)

C:\Users\Lee\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(hidden_layer_sizes=(10, 10, 10))

In [48]:
# Evaluation
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[11  1  0]
 [ 0 12  0]
 [ 0  0 14]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        12
           1       0.92      1.00      0.96        12
           2       1.00      1.00      1.00        14

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

